# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OOP2_FINAL(object):
    def setupUi(self, OOP2_FINAL):
        OOP2_FINAL.setObjectName("OOP2_FINAL")
        OOP2_FINAL.resize(1604, 736)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/application_office_symantec_2477.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OOP2_FINAL.setWindowIcon(icon)
        OOP2_FINAL.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(OOP2_FINAL)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.Source_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Source_groupBox.sizePolicy().hasHeightForWidth())
        self.Source_groupBox.setSizePolicy(sizePolicy)
        self.Source_groupBox.setObjectName("Source_groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Source_groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.File_OpenSource_button = QtWidgets.QPushButton(self.Source_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File_OpenSource_button.sizePolicy().hasHeightForWidth())
        self.File_OpenSource_button.setSizePolicy(sizePolicy)
        self.File_OpenSource_button.setMinimumSize(QtCore.QSize(32, 32))
        self.File_OpenSource_button.setMaximumSize(QtCore.QSize(32, 32))
        self.File_OpenSource_button.setToolTipDuration(-1)
        self.File_OpenSource_button.setStyleSheet("")
        self.File_OpenSource_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/folder_open_icon_135604.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.File_OpenSource_button.setIcon(icon1)
        self.File_OpenSource_button.setIconSize(QtCore.QSize(29, 29))
        self.File_OpenSource_button.setAutoDefault(False)
        self.File_OpenSource_button.setFlat(True)
        self.File_OpenSource_button.setObjectName("File_OpenSource_button")
        self.horizontalLayout.addWidget(self.File_OpenSource_button)
        spacerItem2 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.File_ExportAs_Source_button = QtWidgets.QPushButton(self.Source_groupBox)
        self.File_ExportAs_Source_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File_ExportAs_Source_button.sizePolicy().hasHeightForWidth())
        self.File_ExportAs_Source_button.setSizePolicy(sizePolicy)
        self.File_ExportAs_Source_button.setMinimumSize(QtCore.QSize(32, 32))
        self.File_ExportAs_Source_button.setMaximumSize(QtCore.QSize(32, 32))
        self.File_ExportAs_Source_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/png_3304.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.File_ExportAs_Source_button.setIcon(icon2)
        self.File_ExportAs_Source_button.setIconSize(QtCore.QSize(29, 29))
        self.File_ExportAs_Source_button.setFlat(True)
        self.File_ExportAs_Source_button.setObjectName("File_ExportAs_Source_button")
        self.horizontalLayout.addWidget(self.File_ExportAs_Source_button)
        spacerItem3 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.Edit_Clear_Source_button = QtWidgets.QPushButton(self.Source_groupBox)
        self.Edit_Clear_Source_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edit_Clear_Source_button.sizePolicy().hasHeightForWidth())
        self.Edit_Clear_Source_button.setSizePolicy(sizePolicy)
        self.Edit_Clear_Source_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Edit_Clear_Source_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Edit_Clear_Source_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/seo-social-web-network-internet_324_icon-icons.com_61523.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Edit_Clear_Source_button.setIcon(icon3)
        self.Edit_Clear_Source_button.setIconSize(QtCore.QSize(29, 29))
        self.Edit_Clear_Source_button.setFlat(True)
        self.Edit_Clear_Source_button.setObjectName("Edit_Clear_Source_button")
        self.horizontalLayout.addWidget(self.Edit_Clear_Source_button)
        spacerItem4 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout_6.addWidget(self.Source_groupBox)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.Output_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Output_groupBox.sizePolicy().hasHeightForWidth())
        self.Output_groupBox.setSizePolicy(sizePolicy)
        self.Output_groupBox.setObjectName("Output_groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Output_groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.File_Save_Output_button = QtWidgets.QPushButton(self.Output_groupBox)
        self.File_Save_Output_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File_Save_Output_button.sizePolicy().hasHeightForWidth())
        self.File_Save_Output_button.setSizePolicy(sizePolicy)
        self.File_Save_Output_button.setMinimumSize(QtCore.QSize(32, 32))
        self.File_Save_Output_button.setMaximumSize(QtCore.QSize(32, 32))
        self.File_Save_Output_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/savetheapplication_guardar_2958.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.File_Save_Output_button.setIcon(icon4)
        self.File_Save_Output_button.setIconSize(QtCore.QSize(29, 29))
        self.File_Save_Output_button.setFlat(True)
        self.File_Save_Output_button.setObjectName("File_Save_Output_button")
        self.horizontalLayout_2.addWidget(self.File_Save_Output_button)
        spacerItem7 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.File_SaveAs_Output_button = QtWidgets.QPushButton(self.Output_groupBox)
        self.File_SaveAs_Output_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File_SaveAs_Output_button.sizePolicy().hasHeightForWidth())
        self.File_SaveAs_Output_button.setSizePolicy(sizePolicy)
        self.File_SaveAs_Output_button.setMinimumSize(QtCore.QSize(32, 32))
        self.File_SaveAs_Output_button.setMaximumSize(QtCore.QSize(32, 32))
        self.File_SaveAs_Output_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/save_3621.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.File_SaveAs_Output_button.setIcon(icon5)
        self.File_SaveAs_Output_button.setIconSize(QtCore.QSize(29, 29))
        self.File_SaveAs_Output_button.setFlat(True)
        self.File_SaveAs_Output_button.setObjectName("File_SaveAs_Output_button")
        self.horizontalLayout_2.addWidget(self.File_SaveAs_Output_button)
        spacerItem8 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.File_ExportAs_Output_button = QtWidgets.QPushButton(self.Output_groupBox)
        self.File_ExportAs_Output_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File_ExportAs_Output_button.sizePolicy().hasHeightForWidth())
        self.File_ExportAs_Output_button.setSizePolicy(sizePolicy)
        self.File_ExportAs_Output_button.setMinimumSize(QtCore.QSize(32, 32))
        self.File_ExportAs_Output_button.setMaximumSize(QtCore.QSize(32, 32))
        self.File_ExportAs_Output_button.setText("")
        self.File_ExportAs_Output_button.setIcon(icon2)
        self.File_ExportAs_Output_button.setIconSize(QtCore.QSize(29, 29))
        self.File_ExportAs_Output_button.setFlat(True)
        self.File_ExportAs_Output_button.setObjectName("File_ExportAs_Output_button")
        self.horizontalLayout_2.addWidget(self.File_ExportAs_Output_button)
        spacerItem9 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.Edit_Clear_Output_button = QtWidgets.QPushButton(self.Output_groupBox)
        self.Edit_Clear_Output_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edit_Clear_Output_button.sizePolicy().hasHeightForWidth())
        self.Edit_Clear_Output_button.setSizePolicy(sizePolicy)
        self.Edit_Clear_Output_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Edit_Clear_Output_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Edit_Clear_Output_button.setText("")
        self.Edit_Clear_Output_button.setIcon(icon3)
        self.Edit_Clear_Output_button.setIconSize(QtCore.QSize(29, 29))
        self.Edit_Clear_Output_button.setFlat(True)
        self.Edit_Clear_Output_button.setObjectName("Edit_Clear_Output_button")
        self.horizontalLayout_2.addWidget(self.Edit_Clear_Output_button)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.Edit_Undo_Output_button = QtWidgets.QPushButton(self.Output_groupBox)
        self.Edit_Undo_Output_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edit_Undo_Output_button.sizePolicy().hasHeightForWidth())
        self.Edit_Undo_Output_button.setSizePolicy(sizePolicy)
        self.Edit_Undo_Output_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Edit_Undo_Output_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Edit_Undo_Output_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/undo_icon_128260.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Edit_Undo_Output_button.setIcon(icon6)
        self.Edit_Undo_Output_button.setIconSize(QtCore.QSize(29, 29))
        self.Edit_Undo_Output_button.setFlat(True)
        self.Edit_Undo_Output_button.setObjectName("Edit_Undo_Output_button")
        self.horizontalLayout_2.addWidget(self.Edit_Undo_Output_button)
        spacerItem11 = QtWidgets.QSpacerItem(19, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.Edit_Redo_Output_button = QtWidgets.QPushButton(self.Output_groupBox)
        self.Edit_Redo_Output_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edit_Redo_Output_button.sizePolicy().hasHeightForWidth())
        self.Edit_Redo_Output_button.setSizePolicy(sizePolicy)
        self.Edit_Redo_Output_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Edit_Redo_Output_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Edit_Redo_Output_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/redo_icon_128257.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Edit_Redo_Output_button.setIcon(icon7)
        self.Edit_Redo_Output_button.setIconSize(QtCore.QSize(29, 29))
        self.Edit_Redo_Output_button.setFlat(True)
        self.Edit_Redo_Output_button.setObjectName("Edit_Redo_Output_button")
        self.horizontalLayout_2.addWidget(self.Edit_Redo_Output_button)
        spacerItem12 = QtWidgets.QSpacerItem(19, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.horizontalLayout_6.addWidget(self.Output_groupBox)
        spacerItem13 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem13)
        self.Conversion_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Conversion_groupBox.sizePolicy().hasHeightForWidth())
        self.Conversion_groupBox.setSizePolicy(sizePolicy)
        self.Conversion_groupBox.setObjectName("Conversion_groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Conversion_groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem14 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.Conversion_RGB_to_Grayscale_button = QtWidgets.QPushButton(self.Conversion_groupBox)
        self.Conversion_RGB_to_Grayscale_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Conversion_RGB_to_Grayscale_button.sizePolicy().hasHeightForWidth())
        self.Conversion_RGB_to_Grayscale_button.setSizePolicy(sizePolicy)
        self.Conversion_RGB_to_Grayscale_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Conversion_RGB_to_Grayscale_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Conversion_RGB_to_Grayscale_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/Conversion_icon-icons.com_51175.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Conversion_RGB_to_Grayscale_button.setIcon(icon8)
        self.Conversion_RGB_to_Grayscale_button.setIconSize(QtCore.QSize(29, 29))
        self.Conversion_RGB_to_Grayscale_button.setFlat(True)
        self.Conversion_RGB_to_Grayscale_button.setObjectName("Conversion_RGB_to_Grayscale_button")
        self.horizontalLayout_3.addWidget(self.Conversion_RGB_to_Grayscale_button)
        spacerItem15 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.Conversion_RGB_to_HSV_button = QtWidgets.QPushButton(self.Conversion_groupBox)
        self.Conversion_RGB_to_HSV_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Conversion_RGB_to_HSV_button.sizePolicy().hasHeightForWidth())
        self.Conversion_RGB_to_HSV_button.setSizePolicy(sizePolicy)
        self.Conversion_RGB_to_HSV_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Conversion_RGB_to_HSV_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Conversion_RGB_to_HSV_button.setText("")
        self.Conversion_RGB_to_HSV_button.setIcon(icon8)
        self.Conversion_RGB_to_HSV_button.setIconSize(QtCore.QSize(29, 29))
        self.Conversion_RGB_to_HSV_button.setFlat(True)
        self.Conversion_RGB_to_HSV_button.setObjectName("Conversion_RGB_to_HSV_button")
        self.horizontalLayout_3.addWidget(self.Conversion_RGB_to_HSV_button)
        spacerItem16 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.horizontalLayout_6.addWidget(self.Conversion_groupBox)
        spacerItem17 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.Segmentation_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Segmentation_groupBox.sizePolicy().hasHeightForWidth())
        self.Segmentation_groupBox.setSizePolicy(sizePolicy)
        self.Segmentation_groupBox.setObjectName("Segmentation_groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Segmentation_groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem18 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.Segmentation_Multi_Otsu_Thresholding_button = QtWidgets.QPushButton(self.Segmentation_groupBox)
        self.Segmentation_Multi_Otsu_Thresholding_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Segmentation_Multi_Otsu_Thresholding_button.sizePolicy().hasHeightForWidth())
        self.Segmentation_Multi_Otsu_Thresholding_button.setSizePolicy(sizePolicy)
        self.Segmentation_Multi_Otsu_Thresholding_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Segmentation_Multi_Otsu_Thresholding_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Segmentation_Multi_Otsu_Thresholding_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icons/1number_1_3080.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Segmentation_Multi_Otsu_Thresholding_button.setIcon(icon9)
        self.Segmentation_Multi_Otsu_Thresholding_button.setIconSize(QtCore.QSize(29, 29))
        self.Segmentation_Multi_Otsu_Thresholding_button.setFlat(True)
        self.Segmentation_Multi_Otsu_Thresholding_button.setObjectName("Segmentation_Multi_Otsu_Thresholding_button")
        self.horizontalLayout_4.addWidget(self.Segmentation_Multi_Otsu_Thresholding_button)
        spacerItem19 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem19)
        self.Segmentation_Chan_Vese_Segmentation_button = QtWidgets.QPushButton(self.Segmentation_groupBox)
        self.Segmentation_Chan_Vese_Segmentation_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Segmentation_Chan_Vese_Segmentation_button.sizePolicy().hasHeightForWidth())
        self.Segmentation_Chan_Vese_Segmentation_button.setSizePolicy(sizePolicy)
        self.Segmentation_Chan_Vese_Segmentation_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Segmentation_Chan_Vese_Segmentation_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Segmentation_Chan_Vese_Segmentation_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Icons/2number_2_3830.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Segmentation_Chan_Vese_Segmentation_button.setIcon(icon10)
        self.Segmentation_Chan_Vese_Segmentation_button.setIconSize(QtCore.QSize(29, 29))
        self.Segmentation_Chan_Vese_Segmentation_button.setFlat(True)
        self.Segmentation_Chan_Vese_Segmentation_button.setObjectName("Segmentation_Chan_Vese_Segmentation_button")
        self.horizontalLayout_4.addWidget(self.Segmentation_Chan_Vese_Segmentation_button)
        spacerItem20 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem20)
        self.Segmentation_Morphological_Snakes_button = QtWidgets.QPushButton(self.Segmentation_groupBox)
        self.Segmentation_Morphological_Snakes_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Segmentation_Morphological_Snakes_button.sizePolicy().hasHeightForWidth())
        self.Segmentation_Morphological_Snakes_button.setSizePolicy(sizePolicy)
        self.Segmentation_Morphological_Snakes_button.setMinimumSize(QtCore.QSize(32, 32))
        self.Segmentation_Morphological_Snakes_button.setMaximumSize(QtCore.QSize(32, 32))
        self.Segmentation_Morphological_Snakes_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Icons/3number_3_3078.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Segmentation_Morphological_Snakes_button.setIcon(icon11)
        self.Segmentation_Morphological_Snakes_button.setIconSize(QtCore.QSize(29, 29))
        self.Segmentation_Morphological_Snakes_button.setFlat(True)
        self.Segmentation_Morphological_Snakes_button.setObjectName("Segmentation_Morphological_Snakes_button")
        self.horizontalLayout_4.addWidget(self.Segmentation_Morphological_Snakes_button)
        spacerItem21 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem21)
        self.horizontalLayout_6.addWidget(self.Segmentation_groupBox)
        spacerItem22 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem22)
        self.EdgeDetection_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EdgeDetection_groupBox.sizePolicy().hasHeightForWidth())
        self.EdgeDetection_groupBox.setSizePolicy(sizePolicy)
        self.EdgeDetection_groupBox.setObjectName("EdgeDetection_groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.EdgeDetection_groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem23 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem23)
        self.EdgeDetection_Roberts_button = QtWidgets.QPushButton(self.EdgeDetection_groupBox)
        self.EdgeDetection_Roberts_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EdgeDetection_Roberts_button.sizePolicy().hasHeightForWidth())
        self.EdgeDetection_Roberts_button.setSizePolicy(sizePolicy)
        self.EdgeDetection_Roberts_button.setMinimumSize(QtCore.QSize(32, 32))
        self.EdgeDetection_Roberts_button.setMaximumSize(QtCore.QSize(32, 32))
        self.EdgeDetection_Roberts_button.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Icons/1number_1_3831.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EdgeDetection_Roberts_button.setIcon(icon12)
        self.EdgeDetection_Roberts_button.setIconSize(QtCore.QSize(29, 29))
        self.EdgeDetection_Roberts_button.setFlat(True)
        self.EdgeDetection_Roberts_button.setObjectName("EdgeDetection_Roberts_button")
        self.horizontalLayout_5.addWidget(self.EdgeDetection_Roberts_button)
        spacerItem24 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem24)
        self.EdgeDetection_Sobel_button = QtWidgets.QPushButton(self.EdgeDetection_groupBox)
        self.EdgeDetection_Sobel_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EdgeDetection_Sobel_button.sizePolicy().hasHeightForWidth())
        self.EdgeDetection_Sobel_button.setSizePolicy(sizePolicy)
        self.EdgeDetection_Sobel_button.setMinimumSize(QtCore.QSize(32, 32))
        self.EdgeDetection_Sobel_button.setMaximumSize(QtCore.QSize(32, 32))
        self.EdgeDetection_Sobel_button.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Icons/2number_2_3079.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EdgeDetection_Sobel_button.setIcon(icon13)
        self.EdgeDetection_Sobel_button.setIconSize(QtCore.QSize(29, 29))
        self.EdgeDetection_Sobel_button.setFlat(True)
        self.EdgeDetection_Sobel_button.setObjectName("EdgeDetection_Sobel_button")
        self.horizontalLayout_5.addWidget(self.EdgeDetection_Sobel_button)
        spacerItem25 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem25)
        self.EdgeDetection_Scharr_button = QtWidgets.QPushButton(self.EdgeDetection_groupBox)
        self.EdgeDetection_Scharr_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EdgeDetection_Scharr_button.sizePolicy().hasHeightForWidth())
        self.EdgeDetection_Scharr_button.setSizePolicy(sizePolicy)
        self.EdgeDetection_Scharr_button.setMinimumSize(QtCore.QSize(32, 32))
        self.EdgeDetection_Scharr_button.setMaximumSize(QtCore.QSize(32, 32))
        self.EdgeDetection_Scharr_button.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Icons/3number_3_3077.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EdgeDetection_Scharr_button.setIcon(icon14)
        self.EdgeDetection_Scharr_button.setIconSize(QtCore.QSize(29, 29))
        self.EdgeDetection_Scharr_button.setFlat(True)
        self.EdgeDetection_Scharr_button.setObjectName("EdgeDetection_Scharr_button")
        self.horizontalLayout_5.addWidget(self.EdgeDetection_Scharr_button)
        spacerItem26 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem26)
        self.EdgeDetection_Prewitt_button = QtWidgets.QPushButton(self.EdgeDetection_groupBox)
        self.EdgeDetection_Prewitt_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EdgeDetection_Prewitt_button.sizePolicy().hasHeightForWidth())
        self.EdgeDetection_Prewitt_button.setSizePolicy(sizePolicy)
        self.EdgeDetection_Prewitt_button.setMinimumSize(QtCore.QSize(32, 32))
        self.EdgeDetection_Prewitt_button.setMaximumSize(QtCore.QSize(32, 32))
        self.EdgeDetection_Prewitt_button.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Icons/4number_4_3829.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EdgeDetection_Prewitt_button.setIcon(icon15)
        self.EdgeDetection_Prewitt_button.setIconSize(QtCore.QSize(29, 29))
        self.EdgeDetection_Prewitt_button.setFlat(True)
        self.EdgeDetection_Prewitt_button.setObjectName("EdgeDetection_Prewitt_button")
        self.horizontalLayout_5.addWidget(self.EdgeDetection_Prewitt_button)
        spacerItem27 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem27)
        self.horizontalLayout_6.addWidget(self.EdgeDetection_groupBox)
        spacerItem28 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 6)
        spacerItem29 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem29, 1, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem30, 1, 2, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem31, 1, 3, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem32, 1, 5, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem33 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem33)
        self.Source_Image_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Source_Image_groupBox.sizePolicy().hasHeightForWidth())
        self.Source_Image_groupBox.setSizePolicy(sizePolicy)
        self.Source_Image_groupBox.setMinimumSize(QtCore.QSize(561, 541))
        self.Source_Image_groupBox.setObjectName("Source_Image_groupBox")
        self.Source_PixMap = QtWidgets.QLabel(self.Source_Image_groupBox)
        self.Source_PixMap.setGeometry(QtCore.QRect(10, 23, 541, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Source_PixMap.sizePolicy().hasHeightForWidth())
        self.Source_PixMap.setSizePolicy(sizePolicy)
        self.Source_PixMap.setMinimumSize(QtCore.QSize(0, 0))
        self.Source_PixMap.setText("")
        self.Source_PixMap.setObjectName("Source_PixMap")
        self.horizontalLayout_7.addWidget(self.Source_Image_groupBox)
        spacerItem34 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem34)
        self.Output_Image_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Output_Image_groupBox.sizePolicy().hasHeightForWidth())
        self.Output_Image_groupBox.setSizePolicy(sizePolicy)
        self.Output_Image_groupBox.setMinimumSize(QtCore.QSize(561, 541))
        self.Output_Image_groupBox.setObjectName("Output_Image_groupBox")
        self.Output_PixMap = QtWidgets.QLabel(self.Output_Image_groupBox)
        self.Output_PixMap.setGeometry(QtCore.QRect(10, 23, 541, 501))
        self.Output_PixMap.setText("")
        self.Output_PixMap.setObjectName("Output_PixMap")
        self.horizontalLayout_7.addWidget(self.Output_Image_groupBox)
        spacerItem35 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem35)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 6)
        spacerItem36 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem36, 3, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem37, 3, 4, 1, 1)
        OOP2_FINAL.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OOP2_FINAL)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1604, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Export_As = QtWidgets.QMenu(self.menu_File)
        self.menu_Export_As.setObjectName("menu_Export_As")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Clear = QtWidgets.QMenu(self.menu_Edit)
        self.menu_Clear.setEnabled(True)
        self.menu_Clear.setStatusTip("")
        self.menu_Clear.setObjectName("menu_Clear")
        self.menu_Conversion = QtWidgets.QMenu(self.menubar)
        self.menu_Conversion.setObjectName("menu_Conversion")
        self.menuSegmentation = QtWidgets.QMenu(self.menubar)
        self.menuSegmentation.setObjectName("menuSegmentation")
        self.menuEdge_Detection = QtWidgets.QMenu(self.menubar)
        self.menuEdge_Detection.setObjectName("menuEdge_Detection")
        OOP2_FINAL.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OOP2_FINAL)
        self.statusbar.setObjectName("statusbar")
        OOP2_FINAL.setStatusBar(self.statusbar)
        self.File_Open_Source = QtWidgets.QAction(OOP2_FINAL)
        self.File_Open_Source.setIcon(icon1)
        self.File_Open_Source.setObjectName("File_Open_Source")
        self.File_Save_As_Output = QtWidgets.QAction(OOP2_FINAL)
        self.File_Save_As_Output.setCheckable(False)
        self.File_Save_As_Output.setChecked(False)
        self.File_Save_As_Output.setEnabled(False)
        self.File_Save_As_Output.setIcon(icon5)
        self.File_Save_As_Output.setVisible(True)
        self.File_Save_As_Output.setObjectName("File_Save_As_Output")
        self.File_Exit = QtWidgets.QAction(OOP2_FINAL)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Icons/button_exit_15724.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.File_Exit.setIcon(icon16)
        self.File_Exit.setObjectName("File_Exit")
        self.Edit_Undo_Output = QtWidgets.QAction(OOP2_FINAL)
        self.Edit_Undo_Output.setEnabled(False)
        self.Edit_Undo_Output.setIcon(icon6)
        self.Edit_Undo_Output.setObjectName("Edit_Undo_Output")
        self.Edit_Redo_Output = QtWidgets.QAction(OOP2_FINAL)
        self.Edit_Redo_Output.setEnabled(False)
        self.Edit_Redo_Output.setIcon(icon7)
        self.Edit_Redo_Output.setObjectName("Edit_Redo_Output")
        self.Conversion_RGB_to_Grayscale = QtWidgets.QAction(OOP2_FINAL)
        self.Conversion_RGB_to_Grayscale.setEnabled(False)
        self.Conversion_RGB_to_Grayscale.setIcon(icon8)
        self.Conversion_RGB_to_Grayscale.setObjectName("Conversion_RGB_to_Grayscale")
        self.Conversion_RGB_to_HSV = QtWidgets.QAction(OOP2_FINAL)
        self.Conversion_RGB_to_HSV.setEnabled(False)
        self.Conversion_RGB_to_HSV.setIcon(icon8)
        self.Conversion_RGB_to_HSV.setObjectName("Conversion_RGB_to_HSV")
        self.Segmentation_Multi_Otsu_Thresholding = QtWidgets.QAction(OOP2_FINAL)
        self.Segmentation_Multi_Otsu_Thresholding.setEnabled(False)
        self.Segmentation_Multi_Otsu_Thresholding.setIcon(icon9)
        self.Segmentation_Multi_Otsu_Thresholding.setObjectName("Segmentation_Multi_Otsu_Thresholding")
        self.Segmentation_Chan_Vese_Segmentation = QtWidgets.QAction(OOP2_FINAL)
        self.Segmentation_Chan_Vese_Segmentation.setEnabled(False)
        self.Segmentation_Chan_Vese_Segmentation.setIcon(icon10)
        self.Segmentation_Chan_Vese_Segmentation.setObjectName("Segmentation_Chan_Vese_Segmentation")
        self.Segmentation_Morphological_Snakes = QtWidgets.QAction(OOP2_FINAL)
        self.Segmentation_Morphological_Snakes.setEnabled(False)
        self.Segmentation_Morphological_Snakes.setIcon(icon11)
        self.Segmentation_Morphological_Snakes.setObjectName("Segmentation_Morphological_Snakes")
        self.EdgeDetection_Roberts = QtWidgets.QAction(OOP2_FINAL)
        self.EdgeDetection_Roberts.setEnabled(False)
        self.EdgeDetection_Roberts.setIcon(icon12)
        self.EdgeDetection_Roberts.setObjectName("EdgeDetection_Roberts")
        self.EdgeDetection_Sobel = QtWidgets.QAction(OOP2_FINAL)
        self.EdgeDetection_Sobel.setEnabled(False)
        self.EdgeDetection_Sobel.setIcon(icon13)
        self.EdgeDetection_Sobel.setObjectName("EdgeDetection_Sobel")
        self.EdgeDetection_Scharr = QtWidgets.QAction(OOP2_FINAL)
        self.EdgeDetection_Scharr.setEnabled(False)
        self.EdgeDetection_Scharr.setIcon(icon14)
        self.EdgeDetection_Scharr.setObjectName("EdgeDetection_Scharr")
        self.EdgeDetection_Prewitt = QtWidgets.QAction(OOP2_FINAL)
        self.EdgeDetection_Prewitt.setEnabled(False)
        self.EdgeDetection_Prewitt.setIcon(icon15)
        self.EdgeDetection_Prewitt.setObjectName("EdgeDetection_Prewitt")
        self.File_ExportAs_Source = QtWidgets.QAction(OOP2_FINAL)
        self.File_ExportAs_Source.setEnabled(False)
        self.File_ExportAs_Source.setIcon(icon2)
        self.File_ExportAs_Source.setObjectName("File_ExportAs_Source")
        self.File_ExportAs_Output = QtWidgets.QAction(OOP2_FINAL)
        self.File_ExportAs_Output.setEnabled(False)
        self.File_ExportAs_Output.setIcon(icon2)
        self.File_ExportAs_Output.setObjectName("File_ExportAs_Output")
        self.Edit_Clear_Source = QtWidgets.QAction(OOP2_FINAL)
        self.Edit_Clear_Source.setEnabled(False)
        self.Edit_Clear_Source.setIcon(icon3)
        self.Edit_Clear_Source.setObjectName("Edit_Clear_Source")
        self.Edit_Clear_Output = QtWidgets.QAction(OOP2_FINAL)
        self.Edit_Clear_Output.setEnabled(False)
        self.Edit_Clear_Output.setIcon(icon3)
        self.Edit_Clear_Output.setObjectName("Edit_Clear_Output")
        self.File_Save_Output = QtWidgets.QAction(OOP2_FINAL)
        self.File_Save_Output.setEnabled(False)
        self.File_Save_Output.setIcon(icon4)
        self.File_Save_Output.setObjectName("File_Save_Output")
        self.menu_Export_As.addAction(self.File_ExportAs_Source)
        self.menu_Export_As.addAction(self.File_ExportAs_Output)
        self.menu_File.addAction(self.File_Open_Source)
        self.menu_File.addAction(self.File_Save_Output)
        self.menu_File.addAction(self.File_Save_As_Output)
        self.menu_File.addAction(self.menu_Export_As.menuAction())
        self.menu_File.addAction(self.File_Exit)
        self.menu_Clear.addAction(self.Edit_Clear_Source)
        self.menu_Clear.addAction(self.Edit_Clear_Output)
        self.menu_Edit.addAction(self.menu_Clear.menuAction())
        self.menu_Edit.addAction(self.Edit_Undo_Output)
        self.menu_Edit.addAction(self.Edit_Redo_Output)
        self.menu_Conversion.addAction(self.Conversion_RGB_to_Grayscale)
        self.menu_Conversion.addAction(self.Conversion_RGB_to_HSV)
        self.menuSegmentation.addAction(self.Segmentation_Multi_Otsu_Thresholding)
        self.menuSegmentation.addAction(self.Segmentation_Chan_Vese_Segmentation)
        self.menuSegmentation.addAction(self.Segmentation_Morphological_Snakes)
        self.menuEdge_Detection.addAction(self.EdgeDetection_Roberts)
        self.menuEdge_Detection.addAction(self.EdgeDetection_Sobel)
        self.menuEdge_Detection.addAction(self.EdgeDetection_Scharr)
        self.menuEdge_Detection.addAction(self.EdgeDetection_Prewitt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Conversion.menuAction())
        self.menubar.addAction(self.menuSegmentation.menuAction())
        self.menubar.addAction(self.menuEdge_Detection.menuAction())

        self.retranslateUi(OOP2_FINAL)
        QtCore.QMetaObject.connectSlotsByName(OOP2_FINAL)

    def retranslateUi(self, OOP2_FINAL):
        _translate = QtCore.QCoreApplication.translate
        OOP2_FINAL.setWindowTitle(_translate("OOP2_FINAL", "OOP2 Lab Final"))
        self.Source_groupBox.setTitle(_translate("OOP2_FINAL", "Source"))
        self.File_OpenSource_button.setToolTip(_translate("OOP2_FINAL", "Open"))
        self.File_OpenSource_button.setStatusTip(_translate("OOP2_FINAL", "Open"))
        self.File_ExportAs_Source_button.setToolTip(_translate("OOP2_FINAL", "Export As"))
        self.File_ExportAs_Source_button.setStatusTip(_translate("OOP2_FINAL", "Export As"))
        self.Edit_Clear_Source_button.setToolTip(_translate("OOP2_FINAL", "Clear"))
        self.Edit_Clear_Source_button.setStatusTip(_translate("OOP2_FINAL", "Clear"))
        self.Output_groupBox.setTitle(_translate("OOP2_FINAL", "Output"))
        self.File_Save_Output_button.setToolTip(_translate("OOP2_FINAL", "Save"))
        self.File_Save_Output_button.setStatusTip(_translate("OOP2_FINAL", "Save"))
        self.File_SaveAs_Output_button.setToolTip(_translate("OOP2_FINAL", "Save As"))
        self.File_SaveAs_Output_button.setStatusTip(_translate("OOP2_FINAL", "Save As"))
        self.File_ExportAs_Output_button.setToolTip(_translate("OOP2_FINAL", "Export As"))
        self.File_ExportAs_Output_button.setStatusTip(_translate("OOP2_FINAL", "Export As"))
        self.Edit_Clear_Output_button.setToolTip(_translate("OOP2_FINAL", "Clear"))
        self.Edit_Clear_Output_button.setStatusTip(_translate("OOP2_FINAL", "Clear"))
        self.Edit_Undo_Output_button.setToolTip(_translate("OOP2_FINAL", "Undo"))
        self.Edit_Undo_Output_button.setStatusTip(_translate("OOP2_FINAL", "Undo"))
        self.Edit_Redo_Output_button.setToolTip(_translate("OOP2_FINAL", "Redo"))
        self.Edit_Redo_Output_button.setStatusTip(_translate("OOP2_FINAL", "Redo"))
        self.Conversion_groupBox.setTitle(_translate("OOP2_FINAL", "Conversion"))
        self.Conversion_RGB_to_Grayscale_button.setToolTip(_translate("OOP2_FINAL", "RGB to Grayscale"))
        self.Conversion_RGB_to_Grayscale_button.setStatusTip(_translate("OOP2_FINAL", "RGB to Grayscale"))
        self.Conversion_RGB_to_HSV_button.setToolTip(_translate("OOP2_FINAL", "RGB to HSV"))
        self.Conversion_RGB_to_HSV_button.setStatusTip(_translate("OOP2_FINAL", "RGB to HSV"))
        self.Segmentation_groupBox.setTitle(_translate("OOP2_FINAL", "Segmentation"))
        self.Segmentation_Multi_Otsu_Thresholding_button.setToolTip(_translate("OOP2_FINAL", "Multi Otsu Thresholding"))
        self.Segmentation_Multi_Otsu_Thresholding_button.setStatusTip(_translate("OOP2_FINAL", "Multi Otsu Thresholding"))
        self.Segmentation_Chan_Vese_Segmentation_button.setToolTip(_translate("OOP2_FINAL", "Chan Vese Segmentation"))
        self.Segmentation_Chan_Vese_Segmentation_button.setStatusTip(_translate("OOP2_FINAL", "Chan Vese Segmentation"))
        self.Segmentation_Morphological_Snakes_button.setToolTip(_translate("OOP2_FINAL", "Morphological Snakes"))
        self.Segmentation_Morphological_Snakes_button.setStatusTip(_translate("OOP2_FINAL", "Morphological Snakes"))
        self.EdgeDetection_groupBox.setTitle(_translate("OOP2_FINAL", "Edge Detection"))
        self.EdgeDetection_Roberts_button.setToolTip(_translate("OOP2_FINAL", "Roberts"))
        self.EdgeDetection_Roberts_button.setStatusTip(_translate("OOP2_FINAL", "Roberts"))
        self.EdgeDetection_Sobel_button.setToolTip(_translate("OOP2_FINAL", "Sobel"))
        self.EdgeDetection_Sobel_button.setStatusTip(_translate("OOP2_FINAL", "Sobel"))
        self.EdgeDetection_Scharr_button.setToolTip(_translate("OOP2_FINAL", "Scharr"))
        self.EdgeDetection_Scharr_button.setStatusTip(_translate("OOP2_FINAL", "Scharr"))
        self.EdgeDetection_Prewitt_button.setToolTip(_translate("OOP2_FINAL", "Prewitt"))
        self.EdgeDetection_Prewitt_button.setStatusTip(_translate("OOP2_FINAL", "Prewitt"))
        self.Source_Image_groupBox.setTitle(_translate("OOP2_FINAL", "Source"))
        self.Output_Image_groupBox.setTitle(_translate("OOP2_FINAL", "Output"))
        self.menu_File.setTitle(_translate("OOP2_FINAL", "&File"))
        self.menu_Export_As.setTitle(_translate("OOP2_FINAL", "&Export As"))
        self.menu_Edit.setTitle(_translate("OOP2_FINAL", "&Edit"))
        self.menu_Clear.setTitle(_translate("OOP2_FINAL", "&Clear"))
        self.menu_Conversion.setTitle(_translate("OOP2_FINAL", "&Conversion"))
        self.menuSegmentation.setTitle(_translate("OOP2_FINAL", "&Segmentation"))
        self.menuEdge_Detection.setTitle(_translate("OOP2_FINAL", "&Edge Detection"))
        self.File_Open_Source.setText(_translate("OOP2_FINAL", "&Open Source"))
        self.File_Open_Source.setStatusTip(_translate("OOP2_FINAL", "Open Source"))
        self.File_Open_Source.setShortcut(_translate("OOP2_FINAL", "Ctrl+O"))
        self.File_Save_As_Output.setText(_translate("OOP2_FINAL", "&Save As Output"))
        self.File_Save_As_Output.setStatusTip(_translate("OOP2_FINAL", "Save As Output"))
        self.File_Save_As_Output.setShortcut(_translate("OOP2_FINAL", "Ctrl+Shift+S"))
        self.File_Exit.setText(_translate("OOP2_FINAL", "&Exit"))
        self.File_Exit.setStatusTip(_translate("OOP2_FINAL", "Exit"))
        self.File_Exit.setShortcut(_translate("OOP2_FINAL", "Shift+F4"))
        self.Edit_Undo_Output.setText(_translate("OOP2_FINAL", "&Undo Output"))
        self.Edit_Undo_Output.setStatusTip(_translate("OOP2_FINAL", "Undo Output"))
        self.Edit_Undo_Output.setShortcut(_translate("OOP2_FINAL", "Ctrl+Shift+Z"))
        self.Edit_Redo_Output.setText(_translate("OOP2_FINAL", "&Redo Output"))
        self.Edit_Redo_Output.setStatusTip(_translate("OOP2_FINAL", "Redo Output"))
        self.Edit_Redo_Output.setShortcut(_translate("OOP2_FINAL", "Ctrl+Y"))
        self.Conversion_RGB_to_Grayscale.setText(_translate("OOP2_FINAL", "&RGB to Grayscale"))
        self.Conversion_RGB_to_Grayscale.setStatusTip(_translate("OOP2_FINAL", "RGB to Grayscale"))
        self.Conversion_RGB_to_Grayscale.setShortcut(_translate("OOP2_FINAL", "Ctrl+1"))
        self.Conversion_RGB_to_HSV.setText(_translate("OOP2_FINAL", "&RGB to HSV"))
        self.Conversion_RGB_to_HSV.setStatusTip(_translate("OOP2_FINAL", "RGB to HSV"))
        self.Conversion_RGB_to_HSV.setShortcut(_translate("OOP2_FINAL", "Ctrl+2"))
        self.Segmentation_Multi_Otsu_Thresholding.setText(_translate("OOP2_FINAL", "&Multi-Otsu Thresholding"))
        self.Segmentation_Multi_Otsu_Thresholding.setStatusTip(_translate("OOP2_FINAL", "Multi-Otsu Thresholding"))
        self.Segmentation_Multi_Otsu_Thresholding.setShortcut(_translate("OOP2_FINAL", "Ctrl+4"))
        self.Segmentation_Chan_Vese_Segmentation.setText(_translate("OOP2_FINAL", "&Chan-Vese Segmentation"))
        self.Segmentation_Chan_Vese_Segmentation.setStatusTip(_translate("OOP2_FINAL", "Chan-Vese Segmentation"))
        self.Segmentation_Chan_Vese_Segmentation.setShortcut(_translate("OOP2_FINAL", "Ctrl+5"))
        self.Segmentation_Morphological_Snakes.setText(_translate("OOP2_FINAL", "&Morphological Snakes"))
        self.Segmentation_Morphological_Snakes.setStatusTip(_translate("OOP2_FINAL", "Morphological Snakes"))
        self.Segmentation_Morphological_Snakes.setShortcut(_translate("OOP2_FINAL", "Ctrl+6"))
        self.EdgeDetection_Roberts.setText(_translate("OOP2_FINAL", "&Roberts"))
        self.EdgeDetection_Roberts.setStatusTip(_translate("OOP2_FINAL", "Roberts"))
        self.EdgeDetection_Roberts.setShortcut(_translate("OOP2_FINAL", "Ctrl+7"))
        self.EdgeDetection_Sobel.setText(_translate("OOP2_FINAL", "&Sobel"))
        self.EdgeDetection_Sobel.setStatusTip(_translate("OOP2_FINAL", "Sobel"))
        self.EdgeDetection_Sobel.setShortcut(_translate("OOP2_FINAL", "Ctrl+8"))
        self.EdgeDetection_Scharr.setText(_translate("OOP2_FINAL", "&Scharr"))
        self.EdgeDetection_Scharr.setStatusTip(_translate("OOP2_FINAL", "Scharr"))
        self.EdgeDetection_Scharr.setShortcut(_translate("OOP2_FINAL", "Ctrl+9"))
        self.EdgeDetection_Prewitt.setText(_translate("OOP2_FINAL", "&Prewitt"))
        self.EdgeDetection_Prewitt.setStatusTip(_translate("OOP2_FINAL", "Prewitt"))
        self.EdgeDetection_Prewitt.setShortcut(_translate("OOP2_FINAL", "Ctrl+0"))
        self.File_ExportAs_Source.setText(_translate("OOP2_FINAL", "&Source"))
        self.File_ExportAs_Source.setStatusTip(_translate("OOP2_FINAL", "Source"))
        self.File_ExportAs_Source.setShortcut(_translate("OOP2_FINAL", "Ctrl+D"))
        self.File_ExportAs_Output.setText(_translate("OOP2_FINAL", "&Output"))
        self.File_ExportAs_Output.setStatusTip(_translate("OOP2_FINAL", "Output"))
        self.File_ExportAs_Output.setShortcut(_translate("OOP2_FINAL", "Ctrl+E"))
        self.Edit_Clear_Source.setText(_translate("OOP2_FINAL", "&Source"))
        self.Edit_Clear_Source.setStatusTip(_translate("OOP2_FINAL", "Source"))
        self.Edit_Clear_Source.setShortcut(_translate("OOP2_FINAL", "Ctrl+L"))
        self.Edit_Clear_Output.setText(_translate("OOP2_FINAL", "&Output"))
        self.Edit_Clear_Output.setStatusTip(_translate("OOP2_FINAL", "Output"))
        self.Edit_Clear_Output.setShortcut(_translate("OOP2_FINAL", "Ctrl+Shift+L"))
        self.File_Save_Output.setText(_translate("OOP2_FINAL", "Save Output"))
        self.File_Save_Output.setStatusTip(_translate("OOP2_FINAL", "Save Output"))
        self.File_Save_Output.setShortcut(_translate("OOP2_FINAL", "Ctrl+S"))

